### ISSUE TITLE
Migrate presets tests

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#1006]
```[tasklist]
### Tasks
- [x] Migrate erc20 preset
- [x] Migrate erc721 preset
- [x] Migrate erc1155 preset
- [x] Migrate account presets
- [x] Migrate udc preset
```
