### ISSUE TITLE
Remove DualDispatchers

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/cairo-contracts#1128]
**🧐 Motivation**
They are not supported on live networks and make our library more blotted. 

**📝 Details**
We've had `DualDispatchers` for a while now, and since they are not supported on live networks they haven't been adopted. They are an additional liability in our codebase and make the amount of LOC bigger for any security review. 

```[tasklist]
### Tasks
- [x] Remove access dual dispatchers
- [x] Remove account dual dispatchers
- [x] Remove erc20 dual dispatchers
- [x] Remove erc721 dual dispatchers
- [x] Remove erc1155 dual dispatchers
- [ ] docs and CHANGELOG
```
