### ISSUE TITLE
Migrate test suite to starknet-foundry

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#998]
**🧐 Motivation**
The framework looks mature enough already for us to consider the migration since the default test-runner we are currently using is not the main priority of the compiler team, and is not likely to be as strong feature-wise.

```[tasklist]
### Tasks
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1001
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1002
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1003
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1004
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1005
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1006
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1007
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1008
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1009
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1010
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1011
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1012
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1029
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1072
- [ ] https://github.com/OpenZeppelin/cairo-contracts/issues/1073
```
